# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./QtWidgetsApplication1/Detect.h \
    ./QtWidgetsApplication1/MvCamera.h \
    ./QtWidgetsApplication1/resource.h \
    ./QtWidgetsApplication1/x64/Debug/uic/ui_QtWidgetsApplication1.h \
    ./QtWidgetsApplication1/QtWidgetsApplication1.h \
    ./QtWidgetsApplication1/myLabel.h
SOURCES += ./QtWidgetsApplication1/Detect.cpp \
    ./QtWidgetsApplication1/MvCamera.cpp \
    ./QtWidgetsApplication1/myLabel.cpp \
    ./QtWidgetsApplication1/QtWidgetsApplication1.cpp \
    ./QtWidgetsApplication1/main.cpp
FORMS += ./QtWidgetsApplication1/QtWidgetsApplication1.ui
RESOURCES += QtWidgetsApplication1.qrc
