# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QtWidgetsApplication1
DESTDIR = ../x64/Release
CONFIG += release
LIBS += -L"../../Libraries/win64" \
    -lopencv_world440 \
    -lMvCameraControl
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(../QtWidgetsApplication1.pri)
win32:RC_FILE = QtWidgetsApplication1.rc
